Repository QATCH-Technologies/nanovisQ, pull requests merged in 2025-02, with the labels that each got.

#38 2 follow plate configuration
  QATCH/ui/mainWindow.py
  plate-config.json
Labels: Software, Multiplex

#52 50 caps lock message
  QATCH/core/constants.py
  QATCH/ui/mainWindow.py
  QATCH/ui/mainWindow_ui.py
Labels: documentation, enhancement, Software

#53 Analyze IOB Error Solved with Input Validation
  QATCH/processors/Analyze.py
Labels: bug, Software, Analyze

#59 42 new post processing step
  QATCH/processors/Analyze.py
  QATCH/processors/CurveOptimizer.py
Labels: enhancement, Software, Tag

#56 Analyze with Model Points
  QATCH/processors/Analyze.py
  QATCH/ui/mainWindow.py
  QATCH/ui/runInfo.py
Labels: bug, documentation, enhancement, Software, Analyze, Run Info
